### PR TITLE
feat: allow call expressions on any function-typed value

### LINKED ISSUE #1084: Call-on-index expression `arr[i](args)` is not parsed/resolved
## Symptom

In the closures WEP PR (#1080), the new `closure_generic_bound_fn.wado` fixture originally contained:

```wado
fn dup<F: fn(i32) -> i32>(f: F) -> [F, F] {
    return [f, f];
}

test "dup via generic bound" {
    let n = 10;
    let add_n = |x: i32| x + n;
    let pair = dup(add_n);
    assert pair[0](1) == 11;   // <-- this line failed
    assert pair[1](2) == 12;
}
```

The compiler rejected `pair[0](1)` with:

```
error: unknown function 'unknown'
error: type mismatch: expected '()', found 'i32'
```

I worked around it by binding the indexed value to a local first:

```wado
let f0 = pair[0];
let f1 = pair[1];
assert f0(1) == 11;
assert f1(2) == 12;
```

## Speculation

The user @kt3k suggested wrapping the index expression in parens (`(pair[0])(1)`) may make this work — i.e. the issue may be operator-precedence on the call-on-arbitrary-expression path rather than a true missing-feature.

A clean fix would let any expression of a callable type be directly invoked, regardless of whether it appears as an identifier or as an indexing / field-access / parenthesised expression.

## Repro

Standalone:

```wado
fn pair() -> [fn(i32) -> i32, fn(i32) -> i32] {
    return [|x: i32| x + 1, |x: i32| x * 2];
}

export fn run() {
    let p = pair();
    assert p[0](5) == 6;   // fails today
}
```

## Scope

Out of scope for #1080. Likely a small parser/resolver fix; will tackle in a separate session.

### PR DESCRIPTION
**Pull request by gfx**
Closes #1084.

## Summary

Allow call expressions on any callee whose value type is a function, not
just identifiers. `arr[i](x)`, `(get_fn())(x)`, `(h.f)(x)`,
`(|x: i32| x + 1)(41)`, and nested forms now resolve and compile.

Method-call syntax `foo.bar()` is unaffected: the parser produces a
`MethodCall` AST node, never a `Call` with a `FieldAccess` callee, so
method dispatch keeps Rust's policy (use `(foo.bar)()` to call a
callable field).

## Resolver

The indirect-call dispatch in `resolve_call` is generalized: the
existing identifier-with-fn-type-local path stays, and the
field-access-only path is replaced with one that accepts any
non-identifier callee. Both paths share the same arg resolution, arity
check, typecheck, and `IndirectCall` construction via a new
`build_indirect_call` helper, and both peel references and fn-type
newtypes through a new `as_fn_signature` helper.

An arity check is now enforced on every indirect call. The previous
field-access-only code had none, so misuse silently produced invalid
IR; that loophole is closed.

## Diagnostics

Add `TypeError::CalleeNotCallable`. When a non-identifier callee
resolves successfully but its type is not a function (e.g. `arr[0](5)`
where `arr[0]: i32`), emit *"expression is not callable: type 'T' is
not a function"* instead of the previous misleading *"unknown function
'unknown'"*.

## Tests

New fixtures cover:

- index callee (`p[0](5)`), parenthesised identifier, call result,
  parenthesised field access, nested index, and direct closure-literal
  call.
- arity mismatch on indirect call.
- argument type mismatch on indirect call.
- non-callable callee error message.

`closure_generic_bound_fn.wado` is restored to the direct form from
the original issue — the workaround introduced in #1080 is removed.

## Follow-up

#1098 tracks extending the `fn mut` root-binding check to non-identifier
callees (pre-existing gap, out of scope here).

---
_Generated by [Claude Code](https://claude.ai/code/session_015WrxePgsXKtzjRLvLt6Frh)_

---

<a href="https://app.devin.ai/review/wado-lang/wado/pull/1099" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open in Devin Review
  </picture>
</a>

### CODE REVIEW

File: wado-compiler/tests/fixtures/callable_expr.wado [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    assert pp[0][0](7) == 8;
+    assert pp[1][1](7) == 14;
+}
+
+test "call on closure literal" {
+    assert (|x: i32| x + 1)(41) == 42;
+}
+
+__DATA__
+{"test": {}}
```
[the remark this answers is not in the document]
Comment (gfx) [reply wado-compiler/tests/fixtures/callable_expr.wado:51]: Addressed in bd8f81c0 with a doc comment polish in `tests/e2e.rs`.

For the record: CI did execute the new fixtures (they ship in this PR and CI builds from a clean checkout, so `datatest_mini` rediscovers them at compile time on every run). The touch convention is for local incremental builds where the test binary is already cached.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: wado-compiler/src/unparse.rs [hunk 2]
```diff
@@ -1603,9 +1603,12 @@ impl<'a> Unparser<'a> {
...
     fn unparse_call(&mut self, c: &CallExpr) {
-        // `self.f(args)` would re-parse as a method call, so a field-access
-        // callee must be parenthesized.
-        let needs_parens = matches!(&c.callee, Expr::FieldAccess(_));
+        // Some callee shapes need parentheses to round-trip:
+        // - `FieldAccess`: `self.f(args)` would re-parse as a method call.
+        // - `Closure`: a closure with an expression body greedily consumes
+        //   the rest of the line, so `|x| x + 1(41)` re-parses as
+        //   `|x| (x + 1(41))` rather than calling the closure.
+        let needs_parens = matches!(&c.callee, Expr::FieldAccess(_) | Expr::Closure(_));
```
[the remark this answers is not in the document]
Comment (gfx) [reply wado-compiler/src/unparse.rs]: Verified empirically — see the new `test_roundtrip_ast_call_on_compound_callee` test in bd8f81c0. `Cast`, `If`, `Match`, and `Block` callees all round-trip cleanly without explicit parens.

Why: the parser's postfix loop handles these correctly. For `(f as FnI)(10)`, the cast's type parser stops at the type name (`FnI(10)` is not a valid type), so the trailing `(10)` falls back to the postfix loop as a call on the cast. For `if`/`match`/`{ }` the closing `}` terminates the expression unambiguously before the call's `(`. `Closure` is the only realistic case where the body greedily consumes the call args, so it's the one shape that needs parens.

---
_Generated by [Claude Code](https://claude.ai/code)_

[the remark this answers is not in the document]
Comment (gfx) [reply wado-compiler/src/unparse.rs]: You're right — and my earlier reply was wrong. Apologies for the confusion.

The previous round-trip test was silently skipping: it had a `({ let f = make(); f })(10)` case that the parser rejects (implicit struct literal). That made `format()` return Err, which made `assert_format_preserves_ast` short-circuit without running any assertions. So the test was reporting success while testing nothing.

Verified each shape in isolation (with `(make() as FnI)(10)`, `(-make())(10)`, `(make() + make())(10)`, ...): Cast / Unary / Binary all fail to round-trip, exactly as you said. If / Match are fine because they end with `}`.

Fixed in 036c7ef3 by extending the matcher with `Cast`, `Unary`, `Binary`, `Assign`, `CompoundAssign`, `ComparisonChain`, `Range`, and rewriting the round-trip test with shapes the parser actually accepts. Confirmed the test fails before the fix and passes after.

---
_Generated by [Claude Code](https://claude.ai/code)_
